name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build - Brotli
      run: dotnet build /p:Configuration=Release --no-restore
      working-directory: ./Brotli/
    - name: Build - SevenZip
      run: dotnet build /p:Configuration=Release --no-restore
      working-directory: ./SevenZip/
    - name: Build - AssetRipperCore
      run: dotnet build /p:Configuration=Release --no-restore
      working-directory: ./AssetRipperCore/
    - name: Build - DXShaderRestorer
      run: dotnet build /p:Configuration=Release --no-restore
      working-directory: ./DXShaderRestorer/
    - name: Build - Smolv
      run: dotnet build /p:Configuration=Release --no-restore
      working-directory: ./Smolv/
    - name: Build - SpirV
      run: dotnet build /p:Configuration=Release --no-restore
      working-directory: ./SpirV/
    - name: Build - FMOD x64
      run: dotnet build /p:Configuration=Release -r win-x64
      working-directory: ./FMOD/
    - name: Build - AssetRipperLibrary x64
      run: dotnet build /p:Configuration=Release -r win-x64
      working-directory: ./AssetRipperLibrary/
    - name: Build - AssetRipperConsole x64
      run: dotnet build /p:Configuration=Release -r win-x64
      working-directory: ./AssetRipperConsole/
    - name: Build - AssetRipperGUI x64
      run: dotnet build /p:Configuration=Release -r win-x64
      working-directory: ./AssetRipperGUI/
    - name: Upload AssetRipperConsole
      uses: actions/upload-artifact@v2
      with:
        name: AssetRipperConsole
        path: ./Bins/AssetRipperConsole/Release/x64/publish/AssetRipperConsole*
    - name: Upload AssetRipperGUI
      uses: actions/upload-artifact@v2
      with:
        name: AssetRipperGUI
        path: ./Bins/AssetRipperGUI/Release/x64/publish/AssetRipperGUI*
