name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build x64
      run: dotnet build /p:Configuration=Release /p:Platform=x64
    - name: Upload AssetRipperConsole
      uses: actions/upload-artifact@v2
      with:
        name: AssetRipperConsole
        path: ./Bins/AssetRipperConsole/Release/x64/publish/AssetRipperConsole*
    - name: Upload AssetRipperGUI
      uses: actions/upload-artifact@v2
      with:
        name: AssetRipperGUI
        path: ./Bins/AssetRipperGUI/Release/x64/publish/AssetRipperGUI*
    - name: Test
      run: dotnet test --no-build --verbosity normal
