name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your first issue here. We will try to help you as soon as we can. :)'
        pr-message: 'Thank you for making your first pull request! We greatly appreciate your enthusiam to contribute and will look at this as soon as we can.'
