name: NativeBuild

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure HLSLccWrapper
      run: cmake -B ./build/
      working-directory: ./HLSLccWrapper/
    - name: Build HLSLccWrapper
      run: cmake --build ./build/
      working-directory: ./HLSLccWrapper/

    - name: Configure Texture2DDecoderNative
      run: cmake -B ./build/
      working-directory: ./Texture2DDecoderNative/
    - name: Build Texture2DDecoderNative
      run: cmake --build ./build/
      working-directory: ./Texture2DDecoderNative/
      
    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        name: NativeLibraries_Linux
        path: |
            /home/runner/work/AssetRipper/AssetRipper/HLSLccWrapper/build/libHLSLccWrapper.so
            /home/runner/work/AssetRipper/AssetRipper/Texture2DDecoderNative/build/libTexture2DDecoderNative.so
        if-no-files-found: error