name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  publish_windows_x64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Add Package Source
        run: dotnet nuget add source --name SamBoy "https://nuget.samboy.dev/v3/index.json"

      - name: Publish
        run: dotnet publish /p:PublishProfile=windows_x64
        working-directory: ./Source/AssetRipper.GUI.Free/

      - name: List Files
        shell: bash
        run: ls ./Source/0Bins/Publish/AssetRipper_win_x64

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: AssetRipper_win_x64
          path: ./Source/0Bins/Publish/AssetRipper_win_x64/*.exe
          if-no-files-found: error

  publish_linux_x64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Add Package Source
        run: dotnet nuget add source --name SamBoy "https://nuget.samboy.dev/v3/index.json"

      - name: Publish
        run: dotnet publish /p:PublishProfile=linux_x64
        working-directory: ./Source/AssetRipper.GUI.Free/

      - name: List Files
        shell: bash
        run: ls ./Source/0Bins/Publish/AssetRipper_linux_x64

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: AssetRipper_linux_x64
          path: ./Source/0Bins/Publish/AssetRipper_linux_x64/*.AppImage
          if-no-files-found: error

  publish_mac_x64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Add Package Source
        run: dotnet nuget add source --name SamBoy "https://nuget.samboy.dev/v3/index.json"

      - name: Publish
        run: dotnet publish /p:PublishProfile=mac_x64
        working-directory: ./Source/AssetRipper.GUI.Free/

      - name: List Files
        shell: bash
        run: ls ./Source/0Bins/Publish/AssetRipper_mac_x64

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: AssetRipper_mac_x64
          path: ./Source/0Bins/Publish/AssetRipper_mac_x64/*.dmg
          if-no-files-found: error
