name: Publish

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]

jobs:
   publish_windows_x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Publish AssetRipperConsole Windows x64
      run: dotnet publish /p:PublishProfile=console_windows_x64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperConsole/
      
    - name: Publish AssetRipperGUI Windows x64
      run: dotnet publish /p:PublishProfile=gui_windows_x64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperGUI/
      
    - name: List Console Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperConsole_win_x64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperConsole_win_x64/Licenses/
        date -u > ./Bins/Publish/AssetRipperConsole_win_x64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperConsole_win_x64
      
    - name: Upload AssetRipperConsole Windows x64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperConsole_win_x64
        path: ./Bins/Publish/AssetRipperConsole_win_x64/*
        if-no-files-found: error
        
    - name: List GUI Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperGUI_win_x64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperGUI_win_x64/Licenses/
        date -u > ./Bins/Publish/AssetRipperGUI_win_x64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperGUI_win_x64

    - name: Upload AssetRipperGUI Windows x64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperGUI_win_x64
        path: ./Bins/Publish/AssetRipperGUI_win_x64/*
        if-no-files-found: error

        
   publish_windows_arm64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Publish AssetRipperConsole Windows arm64
      run: dotnet publish /p:PublishProfile=console_windows_arm64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperConsole/
      
    - name: Publish AssetRipperGUI Windows arm64
      run: dotnet publish /p:PublishProfile=gui_windows_arm64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperGUI/
      
    - name: List Console Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperConsole_win_arm64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperConsole_win_arm64/Licenses/
        date -u > ./Bins/Publish/AssetRipperConsole_win_arm64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperConsole_win_arm64
      
    - name: Upload AssetRipperConsole Windows arm64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperConsole_win_arm64
        path: ./Bins/Publish/AssetRipperConsole_win_arm64/*
        if-no-files-found: error
        
    - name: List GUI Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperGUI_win_arm64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperGUI_win_arm64/Licenses/
        date -u > ./Bins/Publish/AssetRipperGUI_win_arm64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperGUI_win_arm64

    - name: Upload AssetRipperGUI Windows arm64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperGUI_win_arm64
        path: ./Bins/Publish/AssetRipperGUI_win_arm64/*
        if-no-files-found: error
      

   publish_linux_x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Publish AssetRipperConsole Linux x64
      run: dotnet publish /p:PublishProfile=console_linux_x64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperConsole/
      
    - name: Publish AssetRipperGUI Linux x64
      run: dotnet publish /p:PublishProfile=gui_linux_x64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperGUI/
        
    - name: List Console Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperConsole_linux_x64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperConsole_linux_x64/Licenses/
        date -u > ./Bins/Publish/AssetRipperConsole_linux_x64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperConsole_linux_x64
        chmod +x ./Bins/Publish/AssetRipperConsole_linux_x64/AssetRipperConsole
      
    - name: Upload AssetRipperConsole Linux x64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperConsole_linux_x64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperConsole_linux_x64/*
        if-no-files-found: error
        
    - name: List GUI Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperGUI_linux_x64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperGUI_linux_x64/Licenses/
        date -u > ./Bins/Publish/AssetRipperGUI_linux_x64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperGUI_linux_x64
        chmod +x ./Bins/Publish/AssetRipperGUI_linux_x64/AssetRipper

    - name: Upload AssetRipperGUI Linux x64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperGUI_linux_x64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperGUI_linux_x64/*
        if-no-files-found: error
      

   publish_linux_arm64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Publish AssetRipperConsole Linux arm64
      run: dotnet publish /p:PublishProfile=console_linux_arm64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperConsole/
      
    - name: Publish AssetRipperGUI Linux arm64
      run: dotnet publish /p:PublishProfile=gui_linux_arm64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperGUI/
        
    - name: List Console Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperConsole_linux_arm64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperConsole_linux_arm64/Licenses/
        date -u > ./Bins/Publish/AssetRipperConsole_linux_arm64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperConsole_linux_arm64
        chmod +x ./Bins/Publish/AssetRipperConsole_linux_arm64/AssetRipperConsole
      
    - name: Upload AssetRipperConsole Linux arm64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperConsole_linux_arm64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperConsole_linux_arm64/*
        if-no-files-found: error
        
    - name: List GUI Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperGUI_linux_arm64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperGUI_linux_arm64/Licenses/
        date -u > ./Bins/Publish/AssetRipperGUI_linux_arm64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperGUI_linux_arm64
        chmod +x ./Bins/Publish/AssetRipperGUI_linux_arm64/AssetRipper

    - name: Upload AssetRipperGUI Linux arm64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperGUI_linux_arm64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperGUI_linux_arm64/*
        if-no-files-found: error


   publish_mac_x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Publish AssetRipperConsole Mac x64
      run: dotnet publish /p:PublishProfile=console_mac_x64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperConsole/
      
    - name: Publish AssetRipperGUI Mac x64
      run: dotnet publish /p:PublishProfile=gui_mac_x64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperGUI/
        
    - name: List Console Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperConsole_mac_x64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperConsole_mac_x64/Licenses/
        date -u > ./Bins/Publish/AssetRipperConsole_mac_x64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperConsole_mac_x64
        chmod +x ./Bins/Publish/AssetRipperConsole_mac_x64/AssetRipperConsole
      
    - name: Upload AssetRipperConsole Mac x64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperConsole_mac_x64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperConsole_mac_x64/*
        if-no-files-found: error
        
    - name: List GUI Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperGUI_mac_x64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperGUI_mac_x64/Licenses/
        date -u > ./Bins/Publish/AssetRipperGUI_mac_x64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperGUI_mac_x64
        chmod +x ./Bins/Publish/AssetRipperGUI_mac_x64/AssetRipper

    - name: Upload AssetRipperGUI Mac x64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperGUI_mac_x64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperGUI_mac_x64/*
        if-no-files-found: error
        


   publish_mac_arm64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Publish AssetRipperConsole Mac arm64
      run: dotnet publish /p:PublishProfile=console_mac_arm64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperConsole/
      
    - name: Publish AssetRipperGUI Mac arm64
      run: dotnet publish /p:PublishProfile=gui_mac_arm64 /p:EnableCompressionInSingleFile=true
      working-directory: ./AssetRipperGUI/
        
    - name: List Console Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperConsole_mac_arm64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperConsole_mac_arm64/Licenses/
        date -u > ./Bins/Publish/AssetRipperConsole_mac_arm64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperConsole_mac_arm64
        chmod +x ./Bins/Publish/AssetRipperConsole_mac_arm64/AssetRipperConsole
      
    - name: Upload AssetRipperConsole Mac arm64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperConsole_mac_arm64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperConsole_mac_arm64/*
        if-no-files-found: error
        
    - name: List GUI Files
      shell: bash
      run: |
        mkdir -p ./Bins/Publish/AssetRipperGUI_mac_arm64/Licenses
        cp ./Licenses/*.md ./Bins/Publish/AssetRipperGUI_mac_arm64/Licenses/
        date -u > ./Bins/Publish/AssetRipperGUI_mac_arm64/compile_time.txt
        ls -R ./Bins/Publish/AssetRipperGUI_mac_arm64
        chmod +x ./Bins/Publish/AssetRipperGUI_mac_arm64/AssetRipper

    - name: Upload AssetRipperGUI Mac arm64
      uses: actions/upload-artifact@v3
      with:
        name: AssetRipperGUI_mac_arm64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperGUI_mac_arm64/*
        if-no-files-found: error
