name: Build

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build x64
      run: dotnet build /p:Configuration=Release /p:Platform=x64
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
        
    - name: Publish AssetRipperConsole Windows x64
      run: dotnet publish /p:PublishProfile=windows_x64
      working-directory: ./AssetRipperConsole/
    - name: Publish AssetRipperConsole Windows x86
      run: dotnet publish /p:PublishProfile=windows_x86
      working-directory: ./AssetRipperConsole/
      
    - name: Publish AssetRipperGUI x64
      run: dotnet publish /p:PublishProfile=GUI_x64
      working-directory: ./AssetRipperGUI/
    - name: Publish AssetRippeGUI x86
      run: dotnet publish /p:PublishProfile=GUI_x86
      working-directory: ./AssetRipperGUI/
      
    - name: Publish AssetRipperConsole Linux x64
      run: dotnet publish /p:PublishProfile=linux_x64
      working-directory: ./AssetRipperConsole/
    - name: Publish AssetRipperConsole Mac x64
      run: dotnet publish /p:PublishProfile=mac_x64
      working-directory: ./AssetRipperConsole/
      
    - name: Upload AssetRipperConsole Windows x64
      uses: actions/upload-artifact@v2
      with:
        name: AssetRipperConsole_win64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperConsole_win64/*
        if-no-files-found: error
    - name: Upload AssetRipperConsole Windows x86
      uses: actions/upload-artifact@v2
      with:
        name: AssetRipperConsole_win86
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperConsole_win86/*
        if-no-files-found: error
    - name: Upload AssetRipperGUI Windows x64
      uses: actions/upload-artifact@v2
      with:
        name: AssetRipperGUI_win64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipper_win64/*
        if-no-files-found: error
    - name: Upload AssetRipperGUI Windows x86
      uses: actions/upload-artifact@v2
      with:
        name: AssetRipperGUI_win86
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipper_win86/*
        if-no-files-found: error
      
    - name: Upload AssetRipperConsole Linux x64
      uses: actions/upload-artifact@v2
      with:
        name: AssetRipperConsole_linux64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperConsole_linux64/*
        if-no-files-found: error
    - name: Upload AssetRipperConsole Mac x64
      uses: actions/upload-artifact@v2
      with:
        name: AssetRipperConsole_mac64
        path: /home/runner/work/AssetRipper/AssetRipper/Bins/Publish/AssetRipperConsole_mac64/*
        if-no-files-found: error
