name: Mark stale issues and pull requests

on:
  schedule:
  - cron: 15 2 * * *

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue'
        stale-pr-message: 'Stale pull request'
        stale-issue-label: 'no-activity'
        stale-pr-label: 'no-activity'
        days-before-stale: 28
        days-before-close: -1
